#! /bin/sh

bspc rule -r "*"
sxhkd &
# picom -CG &
# devmon &
nm-applet &
compton &
nitrogen --restore &
unclutter &
xrdb -I$HOME ~/.Xresources
xautolock -time 9 -locker slock &
xsetroot -cursor_name left_ptr &
# redshift &
pgrep bspswallow || bspswallow &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5

# super + {h,j,k,l} can focus on floating window
bspc config directional_focus_tightness low

bspc config top_padding         20
bspc config border_width        1
bspc config window_gap          0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true

bspc rule -a Zathura state=tiled
bspc rule -a Pcmanfm desktop='^4'follow=on
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Dia desktop='^5' follow=on
bspc rule -a Chromium desktop='^2'follow=on
bspc rule -a SeaMonkey desktop='^2'follow=on
bspc rule -a SeaMonkey:Download state=floating
bspc rule -a SeaMonkey:Places state=floating
bspc rule -a "Pale moon" desktop='^2'follow=on
# bspc rule -a Screenkey manage=off
